### ISSUE TITLE
"notify function called synchronously" message appears when it shouldn't

### ISSUE THREAD

**Issue by vilterp** [elm-lang/core#344]
The following message shows up for every event after

- a `Debug.crash` (i.e. a bug in the developer's code)
- an uncaught javascript exception (i.e. a bug in a Native module or a core library such as Array)

When, [according to Evan](https://groups.google.com/d/msg/elm-discuss/8RXblDRVjas/8DJNqi9zAQAJ), "That error is only supposed to show up in development if I do something weird (or when someone is doing crazy stuff with Native modules and ports)":

```
The notify function has been called synchronously!
This can lead to frames being dropped
Definitely report this to <https://github.com/elm-lang/Elm/issues>
```

Thus, the vast majority of the time this message is inappropriate because it's a bug in your Elm code or a native module, not a bug in the Elm runtime that you should report to core or the compiler.

Perhaps on a `Debug.crash` or JS exception from a native module, the runtime should print out a message such as "this module has stopped working because of a Debug.crash" or "this module has stopped working because of a native module exception" once, and then go into a crashed state in which it doesn't process any more events or print out any more messages.

**Comment by rtfeldman** [comment]
This can also happens when JS code being invoked via a port crashes, which happens a lot in my line of work. :wink: 

Unfortunately I've had trouble reproducing it minimally, but one way to reliably reproduce it is:

1. Check out the [repro-notify](https://github.com/rtfeldman/dreamwriter/tree/repro-notify) branch of Dreamwriter (which [induces a runtime exception in a port](https://github.com/rtfeldman/dreamwriter/compare/repro-notify))
2. [Build it](https://github.com/rtfeldman/dreamwriter#building).
3. Click "new chapter" (the big plus sign in the lower left) twice.

The first time you click it, it will error out with "Uncaught Error: kaboom!" but subsequent clicks will result in notify being triggered synchronously.

![kamboom](https://cloud.githubusercontent.com/assets/1094080/9242170/46400056-4132-11e5-9c8e-4d403ce648e2.gif)

**Comment by evancz** [comment]
There is no such thing as a `notify` function anymore with 0.17, so it's resolved by removing signals.
