### ISSUE TITLE
How to handle characters outside the BMP

### ISSUE THREAD

**Issue by ianbollinger** [elm-lang/core#387]
Manipulating characters outside the Unicode BMP will produce a crash on the REPL (on Fedora but not Mac OS X):

```
> String.toList (String.fromList [ '😣' ])
```

...or...

```
> Char.fromCode (Char.toCode '😣')
```

results in

```
elm-repl: fd:7: hGetContents: invalid argument (invalid byte sequence)
```

It seems that either:

1. The Elm compiler should issue a syntax error if a character literal falls outside of the BMP.
2. The Elm core library should be made to work with characters outside the BMP (harder, since JavaScript doesn't work well with them either.)

**Comment by evancz** [comment]
Can you provide more info on how BMP works and how other systems handle this. I believe we are using the underlying JS stuff for this, so I'd like to know how they do this as well. Overall, give more context and we can figure it out from there.

**Comment by ianbollinger** [comment]
Well, I'd say it's an Elm problem because the underlying problem is that you can create `Chars` that are four-bytes wide (instead of two-bytes wide) and then do weird things with them. For instance, '😣' is codepoint 0x1F623, but `Char.toCode '😣' /= 0x1F623`. Thus `fromCode` and `toCode` aren't strictly inverse. Another example is String.toList, which will split a 4-byte codepoint down the middle. Finally, `List.length ['😣'] /= String.length (String.fromList ['😣'])`.

**Comment by evancz** [comment]
Okay, going to continue tracking in #725 so we can consider all the string oddities in one place. Thanks for reporting this!

**Comment by martincerny** [comment]
I think the core should give up on Unicode code points/characters and treat strings as sequences of 16bit words. The thing is that the mapping between Unicode code points and characters as perceived by the user is neither total, nor injective, nor surjective and thus determining character boundaries in Unicode strings is difficult and expensive. 

Further, having the correct character boundaries is of little practical importance. For almost all tasks in web development, I simply pass strings around. Further, all common operations (search for substring, search for a BMP character etc.) work without any special consideration for BMP characters. In particular, parsing XML, JSON, etc. works just fine.

The implication for the case above is that  '😣' would be an invalid character constant, while "😣" would be a valid string. If anyone needs fancy character-boundaries-aware text processing and is willing to pay the performance penalty, it should be dealt with in a specialized UTF package.

Sourcing a bit from http://utf8everywhere.org/ :-)

**Comment by feihong** [comment]
In JavaScript, there is an easy way to split strings containing non-BMP characters, but it is not yet widely supported. It's true that `"😀😁😂".split("")` will unfortunately return an array containing 6 elements. However, for browsers that support the spread operator, `[..."😀😁😂"]` always returns `["😀", "😁", "😂"]`. According to MDN, [browser support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) for this use of the spread syntax is overall pretty good, with IE Mobile and Opera being notable exceptions.

There is an alternate, but related, method, which is to define a function like this:

```javascript
function toList(str) {
    let result = []; 
    for (let c of str) { result.push(c) }
    return result;
}
```

Unfortunately, the `for...of` syntax is only a [little better supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of), and will fail on IE Mobile and Opera Mobile.

So a possible solution for fixing `String.toList` is to simply wait for browsers to catch up to the relevant parts of the ES2015 spec, and then use `[...str]` instead of `str.split()`.

**Comment by feihong** [comment]
I also looked into the possibility of implementing `Char.fromCode` using `String.prototype.codePointAt()`. The merit of doing that would be because `String.fromCodePoint("😀".codePointAt(0)) === "😀"`. However, at the time of writing, this is [rather poorly supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt), since not even Chrome on Android has that function.

I should note that there are polyfills:

- [String.prototype.codePointAt polyfill](https://github.com/mathiasbynens/String.prototype.codePointAt)
- [String.prototype.fromCodePoint polyfill](https://github.com/mathiasbynens/String.fromCodePoint)

**Comment by evancz** [comment]
The benefit of my fixes, like in https://github.com/elm-lang/core/commit/bf16ca8a10f29e271d61ca463a1268232e97ac79, is that it has great browser support. No need for any new stuff really. Just gotta learn a bunch of stuff about UTF-16.
