### ISSUE TITLE
Touch events outside of container div throws exception

### ISSUE THREAD

**Issue by endeavour** [elm-lang/core#390]
Consuming Touch.taps causes an exception to be thrown when an Elm moduile is embedded in an HTML page and you tap (or click) outside the container div.

"Uncaught TypeError: Cannot read property 't' of undefined" occurs in the end(e) function.

**Comment by eeue56** [comment]
Can you create a short example of this?

**Comment by endeavour** [comment]
Sure, see this:
https://github.com/endeavour/Elm-Touch-Bug-Repro

**Comment by endeavour** [comment]
Run elm-reactor and then browse to bug.html and click on the red div

**Comment by eeue56** [comment]
Looks like the problem is down fact `touchstart` isn't called, but `touchend` is when the listener is added to the node Elm is running inside. I've made a PR #400 which should fix this.

A possibly related problem is when you fire `touch` events onto an element that re-renders itself before you stop touching (i.e trigger `touchend`), then `touchend` is never called, meaning until you click again it there will be no signal sent to clear the data. To try this, load the example project up in Chrome, open the dev tools and enable mobile view, with stimulated touch events, and click on the `[]` in the webpage. I'll make a new issue for that.

**Comment by endeavour** [comment]
Thank you!

**Comment by jvoigtlaender** [comment]
Does #400 fix this completely? Can the issue itself be closed, then?

**Comment by evancz** [comment]
No more `Touch`
