### ISSUE TITLE
Mouse.isDown is not just the left button

### ISSUE THREAD

**Issue by shaleh** [elm-lang/core#43]
The comment in the source says

    {-| The current state of the left mouse-button.
    True when the button is down, and false otherwise. -}

But in reality it is ANY mouse button. This leads to misbehaviour as described in issue elm-lang/elm-lang.org#184. jQuery's docs say:

    The mousedown event is sent when any mouse button is clicked. To act only on specific
    buttons, we can use the event object's which property. Not all browsers support this property
    (Internet Explorer uses button instead), but jQuery normalizes the property so that it is safe
    to use in any browser. The value of which will be 1 for the left button, 2 for the middle button,
    or 3 for the right button.

**Comment by jonathanhefner** [comment]
Here are some reasonably not-horrible cross-browser solutions for detecting which mouse button: http://stackoverflow.com/questions/3944122/detect-left-mouse-button-press

One of the comments there mentions a newer `event.buttons` property which is sufficient by itself, and seems to be supported by current versions of Firefox and Webkit, and by IE 9+:

* https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent.buttons
* https://msdn.microsoft.com/en-us/library/ie/ff974878%28v=vs.85%29.aspx

What is Elm's policy on legacy browser support?

**Comment by TheSeamau5** [comment]
+1 for having both `Mouse.left` and `Mouse.right`. 

As for the general case, I think that having the union type of `MouseButton` is best left for a library. I think we should match the same behavior as Javascript where we have a signal called `Mouse.button` which outputs : 

* -1: No button pressed
* 0 : Main button pressed, usually the left button
* 1 : Auxiliary button pressed, usually the wheel button or themiddle button (if present)
* 2 : Secondary button pressed, usually the right button
* 3 : Fourth button, typically the Browser Back button
* 4 : Fifth button, typically the Browser Forward button

(from [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button))

This is the same kind of logic behind the use of strings for attributes in elm-html as opposed to union types. It allows for the core library to follow the spec as much as possible and then someone can write a "elm-mouse-types" library or something. 

Finally, as for legacy browsers, again, it would be up to a library. I would recommend Elm to just focus on the spec. In this case it is just a matter of jumbling some numbers around. 

That said, I would recommend normalizing `Mouse.left` and `Mouse.right` due to how commonly they are used and doing so like jQuery.

**Comment by kasbah** [comment]
In [Helm](https://github.com/switchface/helm) we have something like:
```haskell
data MouseButton
  = LeftMouse
  | MiddleMouse
  | RightMouse
  | X1Mouse
  | X2Mouse

isDownButton :: MouseButton -> Signal Bool
```

`isDownButton` used to be called `isDown` but I renamed it and introduced the following to bring it closer to Elm.

```haskell
isDown :: Signal Bool
isDown = isDownButton LeftMouse
```

**Comment by evancz** [comment]
Not sure the solution, but this stuff lives in `elm-lang/mouse` now
