### ISSUE TITLE
People are pointed to a non-existing repo

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/core#430]
What repo should https://github.com/elm-lang/core/blob/7ef42ccda13bb5f884330b9da0b283a95e1ec040/src/Native/Runtime.js#L59 be pointing to? Is it elm-reactor? Or core?

**Comment by evancz** [comment]
I think the message needs to be changed.

It was written at a time when I wasn't sure if there were bugs in the implementation of signals. If there were, you would hit this.

Nowadays, pretty much every report that mentions this is due to a problem somewhere not in the compiler or core. Maybe that is user code, maybe that is elm-reactor doing bad things.

So I think the best thing to do would be to reformulate the message to help people understand what went wrong in their stuff. We can pretend the elm-reactor stuff is fixed. Can you try to find all the issues (open or closed) on elm-compiler that came from this message? From there we can try to craft something more helpful.

**Comment by jvoigtlaender** [comment]
This seems to be the list of issues (open or closed) on elm-compiler that came from this message:
* https://github.com/elm-lang/elm-compiler/issues/1122
* https://github.com/elm-lang/elm-compiler/issues/1014
* https://github.com/elm-lang/elm-compiler/issues/946
* https://github.com/elm-lang/elm-compiler/issues/909
* https://github.com/elm-lang/elm-compiler/issues/873
* https://github.com/elm-lang/elm-compiler/issues/872
* https://github.com/elm-lang/elm-compiler/issues/859
* https://github.com/elm-lang/elm-compiler/issues/812
* https://github.com/elm-lang/elm-compiler/issues/444

**Comment by rtfeldman** [comment]
Exceptions thrown from subscription callbacks in JS ports are by far the most common culprit here in my experience, for what it's worth.
