### ISSUE TITLE
Outgoing ports do not automatically convert Maybe anymore

### ISSUE THREAD

**Issue by CumpsD** [elm-lang/core#606]
As of 0.17, outgoing ports do not automatically convert Maybe anymore. According to the docs at http://guide.elm-lang.org/interop/javascript.html#customs-and-border-protection and the behaviour in 0.16 they should be.

For example:

```
type alias Options =
   { responseType : String
   , rememberLastLogin : Maybe Bool
   , closable : Maybe Bool
   , popup : Maybe Bool
   , sso : Maybe Bool
   , callbackURL : Maybe String
   , authParams: { scope: String }
   }
```

and later

```
auth0Options : Options
auth0Options =
  { responseType = "token"
  , callbackURL = Nothing -- "http://localhost:3000"
  , rememberLastLogin = Just True
  , closable = Just False
  , popup = Just False
  , sso = Just True
  , authParams = { scope = "openid" }
  }
```

results in:
![image](https://cloud.githubusercontent.com/assets/1201644/15302800/0d72fee6-1bb5-11e6-9a03-f7e8b20090b1.png)

While it should result in a `callbackURL` of `null` and a `closable` of `false`

**Comment by neoeinstein** [comment]
Confirmed that the related behavior in 0.16 would have translated the `callbackUrl = Nothing` to `null` and the `closable = Just False` to `false`.

Format of the outgoing port in this instance: 

```elm
port auth0showLock : Auth0.Options -> Cmd msg
```

**Comment by neoeinstein** [comment]
Just did my own review of this, and things seemed to work fine for me. I saw the appropriate generated code:
![screen shot 05-16-16 at 05 05 pm](https://cloud.githubusercontent.com/assets/18165/15304074/3d46801a-1b89-11e6-9bc6-e645797fdeb4.PNG)
![screen shot 05-16-16 at 05 04 pm](https://cloud.githubusercontent.com/assets/18165/15304071/36151554-1b89-11e6-8344-ad23f0dab045.PNG)

And the appropriate conversion happening:
![image](https://cloud.githubusercontent.com/assets/18165/15304087/5a7e8e3e-1b89-11e6-8c1d-08ce99d1173a.png)
![image](https://cloud.githubusercontent.com/assets/18165/15304092/659dfed0-1b89-11e6-821a-2cd40b0a41d2.png)

Could this possibly be due to Elm not rebuilding a dirty module? You can try deleting elm-stuff/build-artifacts and that should trigger a rebuild of all modules.

**Comment by CumpsD** [comment]
I removed it all, and tried again but still have the same problem.

This is the code which causes it: https://github.com/exira/admin

```
git clone https://github.com/exira/admin.git
npm install
elm-package install -y
gulp
```

**Comment by evancz** [comment]
Can you open this on the `elm-compiler` repo instead? This is not related to core libraries.

Also, is there any way you can get an http://sscce.org/ that does not require cloning a ton of files? Getting it down to something small makes it much easier to resolve, and it'll be more clear why @neoeinstein could not replicate the problem.

**Comment by evancz** [comment]
Given the state of this, I think it makes sense to close and wait for another report of the issue on `elm-compiler`.
