### ISSUE TITLE
Naming or shadowing issue with `arguments` field in record sent through port

### ISSUE THREAD

**Issue by schpaa** [elm-lang/core#611]
### I want to send `MyRecord` through a port. But it fails with the console message:

`TypeError: undefined is not an object (evaluating 'xs.ctor')`

This is what I'm doing, javascript first:

``` javascript
app.ports.apiv1.subscribe(function(commandRecord) {
    console.log("app.ports.api... ",commandRecord)
})
```

in some port module I have defined the port:

``` elm
port apiv1 : MyRecord -> Cmd a
```

where `MyRecord` is defined as:

``` elm
type alias MyRecord =
    { command : String
    , arguments : List String
    }
```

somewhere in the view-function, this happens:

``` elm
...
in
    flexDiv
        <| [ button [ onClick SendApiV1Message ] [ text "Send api message" ]
```

supported by my update-function:

``` elm
...
case msg of
    SendApiV1Message ->
        let
            x : MyRecord
            x = { command = "Hello", arguments = [ "one", "tow", "three" ] }
        in
            model ! [ apiv1 x ]
...
```
### To fix/bypass

If I change `MyRecord` and substitute the `List String` with a `String`, like this:

``` elm
type alias MyRecord =
    { command : String
    , arguments : String
    }
```

there are no messages in the console, and the program works.

**Comment by schpaa** [comment]
Investigating further, this peculiar thing revealed itself to me:

Gives back `arguments` as `undefined` in the browser-console, all the other works.
```elm
type alias MyRecord =
    { command : String
    , arguments : String
    , extra : Int
    }
```

This one works, any shadowing happening with `arguments` here?

```elm
type alias MyRecord =
    { command : String
    , argumentodos : String
    , extra : Int
    }
```

**Comment by jvoigtlaender** [comment]
Related to https://github.com/elm-lang/elm-compiler/issues/994?

**Comment by schpaa** [comment]
Yes, it seems so. What should I do?

**Comment by jvoigtlaender** [comment]
I think: Open a new issue at the https://github.com/elm-lang/elm-compiler repository. Put an http://sscce.org/ into the first comment on that new issue.

If possible, try to capture the "old" case from https://github.com/elm-lang/elm-compiler/issues/994 as well. (It seems that your problem is about outgoing ports, whereas the one originally reported there was about incoming ports. But the base problem, reserved JS names in stuff going through ports, seems to be the same. So it would be great if you could cover both, since the underlying bug for both might be the same. That probably means you would have to come up with two SSCCEs.)

**Comment by evancz** [comment]
Tracking in https://github.com/elm-lang/elm-compiler/issues/1685 now.

Thank you for the report!
