### ISSUE TITLE
decoding recursive data from JSON hangs

### ISSUE THREAD

**Issue by ContiGuy** [elm-lang/core#665]
Hi, I'm trying to encode and decode a recursive data structure from Json. I have tried several ways to design my structure to be able to decode it from Json but it always hangs. I'm totally new to Elm and functional programming, so please forgive my ignorance.

1. As recommended by the Elm compiler, a record with an embedded indirectly recursive union type. See attachment
[record-with-indirect-recursive-union-hangs-on-json-decode.elm.txt](https://github.com/elm-lang/core/files/366256/record-with-indirect-recursive-union-hangs-on-json-decode.elm.txt)

2. then I tried to redesign the structure to primarily use a (directly) recursive union type because that seemed to work but when I expanded it a little it also hangs while decoding Json. 
[direct-recursive-union-with-record-hangs-on-json-decode.elm.txt](https://github.com/elm-lang/core/files/366257/direct-recursive-union-with-record-hangs-on-json-decode.elm.txt)

This one is especially interesting because by making a tiny change in a let expression it can be switched from working to hanging and back. Please see the other attachment.

It would be really great if someone could fix the problem or suggest a workaround.
Thank you very much!

Browser: Firefox 47.0
Elm: 0.17.1

**Comment by jvoigtlaender** [comment]
You already know about `Json.Decode.Extra.lazy`, otherwise I would have referred you to my response to a similar issue (https://github.com/elm-lang/core/issues/664) a few hours ago.

Given what you know, the best venue for your question would be a community forum, for example the mailing list. Please see http://elm-lang.org/community for various options.

This issue tracker is really for bugs or things that need change in `core`.
