### ISSUE TITLE
Array.append mutates first argument

### ISSUE THREAD

**Issue by AdamLuotonen** [elm-lang/core#691]
Hi!

I think there is a problem with Array.append, as it mutates the first array parameter sent to it. To reproduce, run the following in elm-repl:

```
> import Array
> a = Array.fromList [1,2,3]
Array.fromList [1,2,3] : Array.Array number
> b = Array.fromList [4,5,6]
Array.fromList [4,5,6] : Array.Array number
> c = Array.append a b
Array.fromList [1,2,3,4,5,6] : Array.Array number
> a
Array.fromList [1,2,3,4,5,6] : Array.Array number
```

a should still be [1,2,3] here? I'm running Elm 0.17.1 on Windows.

**Comment by lukewestby** [comment]
Referencing #649

**Comment by evancz** [comment]
I added this to #649, track there. Also, there is progress on a mostly Elm implementation that should fix a lot of these issues!

**Comment by eike** [comment]
Since this problem still exists in Elm 0.18 (try
~~~
import Array
import Html exposing (..)

a = Array.fromList ["foo"]
b = Array.fromList ["bar"]
c = Array.append a b

main = div []
  [ text (toString a)
  , text (toString b)
  , text (toString c)
  ]
~~~
on elm-lang.org/try, for example, I think it would be a good idea to mention so in the documentation of Array.

**Comment by ronanyeah** [comment]
> I think it would be a good idea to mention so in the documentation of Array.

Or at least this [comment](https://github.com/elm-lang/core/issues/649#issuecomment-314207112) should be clarified.
