### ISSUE TITLE
Runtime error when comparing nested Html of different depths

### ISSUE THREAD

**Issue by lpil** [elm-lang/core#694]
Hello!

Today while trying to do some testing I encounted a runtime error. Here's a recreation.

```elm
> import Html exposing (..)
> (div [] []) == (div [] [])
-- True : Bool

> (div [] [ text "Hi" ]) == (div [] [ text "Hello" ])
-- False : Bool

> (div [] [ text "Hi" ]) == (div [] [])
-- TypeError: Cannot read property 'type' of undefined
```

Elm version 0.17.0, installed via the `elm` package on npm.

Debian Jessie Linux OS.

Running Elm in node v4.1.1 via the REPL.

Here are the entries from my `elm-stuff/exact-dependencies.json`.
```
    "elm-lang/html": "1.1.0",
    "elm-lang/core": "4.0.4"
```

I was pointed over here from https://github.com/elm-lang/elm-compiler/issues/1465

**Comment by evancz** [comment]
Equality is not defined on virtual DOM values, so the fix is going to be modifying the compiler to detect when folks try to use equality in invalid cases (like on functions) and making that an error at compile time. This is already planned, so I'd rather not track the implications of that change here.

**Comment by jvoigtlaender** [comment]
But maybe at least mentioning this in the `core` documentation would be good? Currently, http://package.elm-lang.org/packages/elm-lang/core/4.0.5/Basics#== carries this note:
> **Note:** Equality (in the Elm sense) is not possible for certain types. For example, the functions `(\n -> n + 1)` and `(\n -> 1 + n)` are “the same” but detecting this in general is undecidable. In a future release, the compiler will detect when `(==)` is used with problematic types and provide a helpful error message. This will require quite serious infrastructure work that makes sense to batch with another big project, so the stopgap is to crash as quickly as possible. Problematic types include functions and JavaScript values like `Json.Encode.Value` which could contain functions if passed through a port.

That html values are also of "problematic type" seems important information for users, since trying to test views by comparing html values via `==` is something that is quite tempting. Currently neither the documentation for `core` nor for the `html` package tell users that using `==` on html values is not okay.

**Comment by lpil** [comment]
A compiler error and improved documentation would be wonderful, thanks all.

Given we cannot test equality on html is there another method for testing views? Often I have business logic that results in html that I would love to be able to test.
