### ISSUE TITLE
Runtime Exception with List.append. TypeError: undefined is not an object (evaluating 'xs.ctor')

### ISSUE THREAD

**Issue by That-David-Guy** [elm-lang/core#728]
Version: Elm v0.17

This elm code:

```
-- [1, 2, 3] doesn't matter, it is the two b's that cause the error
b = [1, 2, 3] |> List.append b
-- OR
b = List.append b [1, 2, 3]
-- OR
b = List.append [1, 2, 3] b
```

Cause the following runtime exception (i.e. in my Chrome console window, not the elm compile error message)

```
TypeError: undefined is not an object (evaluating 'xs.ctor')
```

It seems like the bug is because I shouldn't be using 'b' twice like that. Normally I wouldn't log an issue like this (because it was my fault). But since one of Elms selling points is _No Runtime Exceptions_, I thought you might want to know.

Cheers

**Comment by jvoigtlaender** [comment]
This issue has been reported many times. In the next release of Elm, this kind of recursive value definition will be rejected by the compiler.

**Comment by evancz** [comment]
The issue is #873 and will be detected in 0.18 of Elm.

@jvoigtlaender, I know this issue is annoying, but try not to take it out on people who are just trying to be helpful!

**Comment by jvoigtlaender** [comment]
@evancz, I'm sorry, I honestly don't know what you mean. In what way was I taking something out on somebody? I was just giving the best answer I could. Except for not providing the link to the specific issue in the other repo. And that was simply because I was on mobile, where it's more complicated (for me) to insert links. Oh well, I could have not answered at that time and leave it for later. Other than that, I'm afraid you are seeing ghosts (in seeing unfriendliness in my answering).
