### ISSUE TITLE
Documentation: What is an Int?

### ISSUE THREAD

**Issue by expipiplus1** [elm-lang/core#742]
I've been unable to determine what is representable in a value of type `Int` in Elm.

This page seems to suggest that `Int` is a 32bit two's complement integer http://learnyouanelm.github.io/pages/03-types.html

Playing around in the REPL suggests that Int is actually represented as a double precision float. 2^53 is the largest value such that every positive integer below it is representable.

**Comment by sgraf812** [comment]
Also, the usual weird JavaScript hacks exist if you are concerned about precision. I'm making use of this in [`intdict`](https://github.com/elm-community/intdict/blob/master/src/IntDict.elm#L87-L101), requiring the user to make sure they are actually passing valid integers (yuck!).

Perhaps something like this is worthwhile to have in `core`?

**Comment by evancz** [comment]
Because Elm targets JavaScript, there are certain problems with integers that we cannot fix without very severe performance costs. An Elm `Int` should be a 32-bit integer, but there is no such thing in JavaScript. So you can think of this as the compiler being non-compliant. The problem is that compliance is basically impossible until we are targeting WebAssembly directly, or some other platform.

Does that answer your question? Also, I don't know where this should be documented. If someone can find a nice place, maybe it makes sense to do.

**Comment by expipiplus1** [comment]
Would it be possible to keep this issue open until this information finds a place in the documentation?

**Comment by lukewestby** [comment]
This sounds like a good addition to faq.elm-community.org
