### ISSUE TITLE
Text.fromString references missing module

### ISSUE THREAD

**Issue by joshsz** [elm-lang/core#805]
https://github.com/elm-lang/core/blob/master/src/Basics.elm#L472

This document references `Text.fromString`, but the `Text` module is missing and there doesn't seem to be any implementation of `fromString` anymore in core.

I'm not sure where to direct readers to find the functionality in `fromString`, else I'd submit a PR.

**Comment by joshsz** [comment]
Is `Text.fromString` no longer planned to be supported?

**Comment by mgold** [comment]
The `Text` module and type are long gone.

**Comment by joshsz** [comment]
I meant the ability to convert a string into an Elm symbol. 

It would reduce the boilerplate I need in this routing function example:

```
locationUpdate : Navigation.Location -> App.Msg
locationUpdate location =
  case (String.dropLeft 2 location.hash) of

    "ViewDocList" -> ViewState ViewDocList

    "ViewDocument" -> ViewState ViewDocument

    _ -> App.NoOp

    -- Would rather code this as:
    -- msg -> case Text.fromString msg of
    --          Just value -> ViewState value
    --          Nothing    -> App.NoOp
```

Sure I could just pass the strings along into the `ViewState` constructor for the `App.Msg` but somehow that seems contrary to the point of strongly-typed code.

**Comment by mgold** [comment]
There are ways of doing what you want and you should ask on the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss). What you're asking about is not what `Text.fromString` used to do.

**Comment by jvoigtlaender** [comment]
> The `Text` module and type are long gone.

Actually, they are moved: http://package.elm-lang.org/packages/evancz/elm-graphics/1.0.1/Text#fromString

**Comment by joshsz** [comment]
`Text.fromString` in `evancz/elm-graphics` has different functionality (it converts `String -> Text` when I'm looking for `String -> a`)

I'll ask on the mailing list, thanks!

**Comment by jvoigtlaender** [comment]
I know that it has different functionality. I provided the pointer to it so that you can know what functionality it has (in contrast to what you apparently believed its functionality to be - and you saying you don't know where to find it).

In any case, the `Text.fromString` in `evancz/elm-graphics` is *exactly* the `Text.fromString` that the line https://github.com/elm-lang/core/blob/master/src/Basics.elm#L472 you pointed to is referring to. That line still lives on from when the `Text.fromString` that is now in `evancz/elm-graphics` was living inside `elm-lang/core`. So one actual fix to the issue you have opened here would indeed be to mention in the comment that the `Text.fromString` referred to can be found in `evancz/elm-graphics`.

**Comment by joshsz** [comment]
my error, thanks for setting me straight.

**Comment by jvoigtlaender** [comment]
Oh, don't worry. No error/problem at all. But maybe let's close this issue here and open a fresh/clean one which just states that the documentation for `Basics.fromString : a -> String` mentions `Text.fromString : String -> Text` without telling the reader where to find `Text.fromString` (namely not within the same package here, instead in `evancz/elm-graphics` now).

**Comment by joshsz** [comment]
Oh np, I think you fixed the documentation bug in https://github.com/elm-lang/core/issues/809, so definitely happy to close :) I've started a thread on the mailing list to discuss further.

Thanks!

**Comment by jvoigtlaender** [comment]
No, no, in #809 the bug is not fixed at all. I closed that PR because it wasn't a fix.

**Comment by dgreensp** [comment]
The docs still reference the non-existent module `Text`, so re-open?

**Comment by jvoigtlaender** [comment]
Re-open what?

**Comment by dgreensp** [comment]
@jvoigtlaender I'm agreeing with you that this issue should be re-opened, since the docs still make reference to the non-existent module `Text` at https://github.com/elm-lang/core/blob/master/src/Basics.elm#L472

**Comment by jvoigtlaender** [comment]
Actually, it would be better to open a fresh one with more focus, as I suggested above.

**Comment by dgreensp** [comment]
Ok.  FWIW, I think the initial issue description states the problem perfectly.  The title seems to be a misprint and should be `Basics.toString references missing module`, but the description is accurate.  There are different possible solutions to the problem; if it were me I would remove or rewrite the offending sentence completely.  It seems odd to reference a graphics library in the docs for `toString`.  The point (I think) is that the String returned matches how the value would be written in source code.  It doesn't matter whether the String is rendered to graphics, rich text, DOM, or logged to the console.

**Comment by jvoigtlaender** [comment]
The initial description is one thing. Subsequent comments lead astray and talk about functionality unrelated to what us actually at issue. Why don't you simply create a new issue?
