### ISSUE TITLE
List.singleton clarity

### ISSUE THREAD

**Issue by tibastral** [elm-lang/core#860]
Hello everybody,

List.singleton seems a little confusing, especially for people coming from OOP. As stated, we want to be mainstream.

Mathematically, List.unit would work as well and would be a little less confusing. [Stack overflow discussion](http://stackoverflow.com/questions/11696344/whats-the-name-of-a-list-with-only-one-element), [Wikipedia](https://en.wikipedia.org/wiki/Singleton_(mathematics))

**Comment by simonewebdesign** [comment]
To be fair, we might as well just remove it.

The [implementation](https://github.com/elm-lang/core/blob/5.1.1/src/List.elm#L529-L531) actually just wraps the value in `[]`, so if the function name is confusing I don't see any point in keeping it.
Are there any use cases for it?

**Comment by tibastral** [comment]
Yes it's useful. It allows to be point free.

**Comment by Angarsk8** [comment]
I was wondering the same today. This is current implementation of the [_`singleton/1`_](https://github.com/elm-lang/core/blob/5.1.1/src/List.elm#L529) function:

```elm
singleton : a -> List a
singleton value =
  [value]
```

IMHO something that simple should not be abstracted, but I'd like to  know the reasons behind its existence, maybe we're all missing something.

**Comment by roine** [comment]
Use case

```
List.map List.singleton [1,2]
>> [[1], [2]]
```

**Comment by turboMaCk** [comment]
It's useful. `List.singleton` is actually `pure` implementation for `List` as a [Applicative](https://en.wikibooks.org/wiki/Haskell/Applicative_functors#The_Applicative_class).

It's useful for lifting function to List context. Unluckilly `andMap` is missing in core and can be found only in [`List.Extra`](http://package.elm-lang.org/packages/elm-community/list-extra/6.1.0/List-Extra#andMap).

Actual questions in my opinion are:

- Does `singleton` makes sense without `andMap`??
- Should `List` in core implement applicative style since most folks don't use it?

**Comment by lukewestby** [comment]
Hey folks, this conversation belongs on elm-discuss or in slack. GitHub issues are for bugs, so as long as `List.singleton` works as advertised discussions about the name should be taken to the mailing list or slack.
