### ISSUE TITLE
Passing `NaN` as a flag results in confusing error message

### ISSUE THREAD

**Issue by ocharles** [elm-lang/core#899]
See https://ellie-app.com/44s93YHd25Wa1/0 which results in

```
Expecting null but instead got: null
```

**Comment by evancz** [comment]
Hello! I am tracking this in https://github.com/elm-lang/elm-compiler/issues/1687 because ports and flags allow the same stuff through. The theory is that grouping related things together will help reveal patterns that would not be apparent if issues were just resolved in order as received. Anyway, thank you for reporting this!
